export const ROUTES = {
  AUTH_LOGIN: '/auth/login',
  AUTH_SIGNUP: '/auth/signup',
  PRIVACY: '/privacy',
  FORBIDDEN: '/forbidden',
  DASHBOARD: '/dashboard',
  BATTERY: '/battery',
  BATTERY_DETAIL: (batteryCellId: string | number) => `/battery/${batteryCellId}`,
  REPORT_INDIVIDUAL: '/reports/individual',
  REPORT_INDIVIDUAL_DETAIL: (reportId: string | number) => `/reports/individual/${reportId}`,
  REPORT_DAILY: '/reports/daily',
  REPORT_DAILY_DETAIL: (reportId: string | number) => `/reports/daily/${reportId}`,
  NOTICE: '/notices',
  NOTICE_CREATE: '/notices/new',
  NOTICE_DETAIL: (id: string | number) => `/notices/${id}`,
  NOTICE_EDIT: (id: string | number) => `/notices/${id}/edit`,
  HELP: '/help',
  SETTINGS: '/settings',
} as const
